//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_ADB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuels
    {
        public int FuelID { get; set; }
        public string FuelType { get; set; }
        public Nullable<float> FuelDensity { get; set; }
    }
}
