//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_ADB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Fuels
    {
        [Display(Name = "Номер топлива")]
        public int FuelID { get; set; }

        [Display(Name = "Тип топлива")]
        public string FuelType { get; set; }

        [Display(Name = "Плотность")]
        public Nullable<float> FuelDensity { get; set; }
    }
}
