//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_ADB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllOperations
    {
        public int OperationID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> TankID { get; set; }
        public Nullable<float> Inc_Exp { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FuelType { get; set; }
        public string TankType { get; set; }
    }
}
